### ISSUE TITLE
This repo looks less developer-friendly without a description and URL to navigate.

### ISSUE THREAD

**Issue by Nishchit14** [200ok-vc/200ok.vc#3]
**Description**: 200 OK Ventures is a friendly community of angel investors who have all worked at early-stage API and platform startups.
**URL**: https://200ok.vc

### without info
![image](https://user-images.githubusercontent.com/5078921/139047340-b6662dbc-20d4-4e2e-af63-70ae4545ee45.png)

### with info
![image](https://user-images.githubusercontent.com/5078921/139048223-3ba60917-7157-44a1-b161-fe5cd46795e0.png)

**Comment by crtr0** [comment]
Thank you, and sorry for the delay. Need to fix my notification settings.
